### ISSUE TITLE
"unistd.h" should be <unistd.h>

### ISSUE THREAD

**Issue by eddieSullivan** [aws-amplify/aws-sdk-ios#5419]
**Describe the bug**
There are two Objective-C source files that `#include "unistd.h"`, however, since this is a system header, it should be `#include <unistd.h>`

Using the double-quotes instead of angle brackets causes the file to be searched for in a different set of directories. This means that if there is a non-system header file of the same name, that one will be included rather than the system file.

In my case, this causes a build failure in my React Native app when I upgrade to React Native version 0.74.5, because the "RCT-Folly" library has its own version of "unistd.h", which AWSCore tries to use.

The Objective-C files in question are:
[AWSCore/FMDB/AWSFMResultSet.m](https://github.com/aws-amplify/aws-sdk-ios/blob/d47b50898dfbe89e2c498422d703275fef5b4b80/AWSCore/FMDB/AWSFMResultSet.m#L3)

and: 

[AWSCore/FMDB/AWSFMDatabase.m](https://github.com/aws-amplify/aws-sdk-ios/blob/d47b50898dfbe89e2c498422d703275fef5b4b80/AWSCore/FMDB/AWSFMDatabase.m#L2)

**To Reproduce**
1. Create a new React Native project with `npx @react-native-community/cli@latest init AwesomeProject --version 0.74.5`
2. `cd AwesomeProject`
3. `npm install`
4. `cd ios`
5. Add `pod 'AWSCore'` to the "AwesomeProject" target in `AwesomeProject/ios/Podfile`
6. `pod install`
7. `xed .` and try to build the workspace in Xcode (I'm on 15.4.0)

**Observed Behavior**
The build fails.

**Expected Behavior**
A successful build.

**Stack Trace**
```
In file included from /home/src/AwesomeProject/ios/Pods/AWSCore/AWSCore/FMDB/AWSFMResultSet.m:3:
/home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:24:1: error: unknown type name 'using'
using off64_t = off_t;
^
/home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:24:17: error: unexpected type name 'off_t': expected expression
using off64_t = off_t;
                ^
/home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:26:1: error: unknown type name 'off64_t'; did you mean 'off_t'?
off64_t lseek64(int fh, off64_t off, int orig);
^~~~~~~
off_t
In module 'Darwin' imported from /home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:21:
/Applications/Xcode-15.4.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/sys/_types/_off_t.h:31:33: note: 'off_t' declared here
typedef __darwin_off_t          off_t;
                                ^
In file included from /home/src/AwesomeProject/ios/Pods/AWSCore/AWSCore/FMDB/AWSFMResultSet.m:3:
/home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:26:25: error: unknown type name 'off64_t'; did you mean 'off_t'?
off64_t lseek64(int fh, off64_t off, int orig);
                        ^~~~~~~
                        off_t
In module 'Darwin' imported from /home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:21:
/Applications/Xcode-15.4.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/sys/_types/_off_t.h:31:33: note: 'off_t' declared here
typedef __darwin_off_t          off_t;
                                ^
In file included from /home/src/AwesomeProject/ios/Pods/AWSCore/AWSCore/FMDB/AWSFMResultSet.m:3:
/home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:28:50: error: unknown type name 'off64_t'; did you mean 'off_t'?
ssize_t pread64(int fd, void* buf, size_t count, off64_t offset);
                                                 ^~~~~~~
                                                 off_t
In module 'Darwin' imported from /home/src/AwesomeProject/ios/Pods/RCT-Folly/folly/portability/Unistd.h:21:
/Applications/Xcode-15.4.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/usr/include/sys/_types/_off_t.h:31:33: note: 'off_t' declared here
typedef __darwin_off_t          off_t;
                                ^
5 errors generated.
```

**Code Snippet**
```
#include "unistd.h"
```

**Unique Configuration**
A React Native app

**Environment(please complete the following information):**
 - SDK Version: 2.35.0
 - Dependency Manager: Cocoapods
 - Xcode Version: 15.4.0

**Comment by pgom** [comment]
@eddieSullivan that tip was really great since I was spending hours debugging an issue related to this. @thisisabhash I'm patching the Pod file with is changing is a solution but having this directly added would be great

**Comment by thisisabhash** [comment]
Thank you for your message - our team will take a look and post updates.

**Comment by decim92** [comment]
Hi, is there a workaround for this? like downgrading react native or AWS?

**Comment by NirN-Venn** [comment]
Getting the same error after updating from rn 0.71.11 to 0.74.5.

**Comment by markgaucher** [comment]
I'm receiving a similar error after upgrading React Native from 0.73.6 to 0.74.5.

**Comment by lawmicha** [comment]
Thanks for the updates, we are investigating this (https://github.com/aws-amplify/aws-sdk-ios/pull/5425) and will provide an update when we can.

**Comment by eddieSullivan** [comment]
In my Podfile I added this to the end of my `post_install` block. It's a hack for sure but it's a temporary workaround:

```
  unistd_file = File.join(__dir__, 'Pods/AWSCore/AWSCore/FMDB/unistd.h')
  unless File.exist?(unistd_file)
    File.open(unistd_file, 'w') do |f|
      f.write("#include <unistd.h>\n")
    end
  end
```

**Comment by thisisabhash** [comment]
The changes are released in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.37.0
